### ISSUE TITLE
Is full cloning required?

### ISSUE THREAD

**Issue by psibi** [fpco/stackage-update#3]
I see here: https://github.com/fpco/stackage-update/blob/299bd1d1ea71196002059da769d352ca0a5b34f3/Stackage/Update.hs#L45 that you are cloning the entire tree. Is that required ?

Why not use shallow clone aka depth --1 ?

**Comment by snoyberg** [comment]
Nice idea, but it doesn't seem to work:

```
Cloning into 'all-cabal-files'...
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
Checking connectivity... done.
fatal: Not a valid object name
Exit code ExitFailure 128 while running ["git","archive","--format=tar","-o","/home/vagrant/.cabal/packages/hackage.haskell.org/00-index.tar","origin/hackage"] in /home/vagrant/.stackage-update/all-cabal-files
```

One thing we could do to improve clone time is to checkout the `display` branch by default, which will avoid creating all of the .cabal files. I think I'll push a commit for that change and see how it works.

**Comment by psibi** [comment]
CC: @snoyberg 

Are you sure it doesn't work for you? Just tested and it works fine for me:

```
sibi::monoid { ~/sibi_fpco/stackage-update/dist/build/stackage-update }-> ./stackage-update
Cloning into 'all-cabal-files'...
remote: Counting objects: 115337, done.        
remote: Compressing objects: 100% (24345/24345), done.        
remote: Total 115337 (delta 44504), reused 115137 (delta 44455), pack-reused 0        
Receiving objects: 100% (115337/115337), 15.43 MiB | 52 KiB/s, done.
Resolving deltas: 100% (44504/44504), done.
```

And just tested in the directory:

```
sibi::monoid { ~/.stackage-update/all-cabal-files }-> git log
commit c16998ef55c19393fca0af5233f1a286a49389c2
Author: Commercial Haskell all-cabal-files Travis job <michael+all-cabal-files@snoyman.com>
Date:   Fri Apr 17 07:20:28 2015 +0000

    Update from Hackage at Fri Apr 17 07:20:28 UTC 2015
```

Just shows one commit.

**Comment by snoyberg** [comment]
What happens when you use `git archive`?

**Comment by psibi** [comment]
I didn't use git archive.  This was the code:

```
runIn suDir suDir "git" ["clone", "--depth", "1", "https://github.com/commercialhaskell/all-cabal-files.git", "-b", "hackage"]
```

**Comment by snoyberg** [comment]
I understand, but the code then proceeds to use `git archive` to produce
the 00-index.tar file, which is where things failed in my testing.

**Comment by psibi** [comment]
There is a `00-index.tar` file in my `~/.cabal/packages/hackage.haskell.org` directory which I guess is created from the `git archive` command. Do you want me to run the git archive command anywhere manually ?

**Comment by snoyberg** [comment]
OK, I must have messed up in my testing, this is now working. I'm going to test a few more days and if everything is working, I'll release it on Sunday.
