### ISSUE TITLE
Unknown git option

### ISSUE THREAD

**Issue by astynax** [fpco/stackage-update#5]
`stackage-update` halts with the message:

``` shell
$ stackage-update 
error: unknown option 'no-single-branch'
usage: git clone [options] [--] <repo> [<dir>]
...
... # usual "git --help" output
...
Exit code ExitFailure 129 while running ["git","clone","https://github.com/commercialhaskell/all-cabal-files.git","-b","display","--depth","1","--no-single-branch"] in /home/user/.stackage-update
```

git version on my machine:

``` shell
$ git --version
git version 1.7.9.5
```

**Comment by snoyberg** [comment]
I'm not sure which version of Git added that feature, so I chose 1.9 as the cutoff. Can you try installing from `master` and let me know if that solves the problem for you?

**Comment by psibi** [comment]
I have exactly `1.7.9.5` and it works for me.

**Comment by snoyberg** [comment]
@psibi It might be that you had a preexisting repo before the recent changes (though I don't think that's the case).

**Comment by astynax** [comment]
Other machine with `stackage-update==0.1.0.0`:

``` shell
$ git --version
git version 1.7.9.5
$ stackage-update
remote: Counting objects: 546, done.
remote: Compressing objects: 100% (243/243), done...
```

At this time app works fine.

**Comment by snoyberg** [comment]
@astynax Does this mean that you're no longer able to reproduce the problem with that version of Git?

**Comment by astynax** [comment]
The application works on one machine (home computer) and don't works on the another (work PC). Both machines have this particular version of git (1.7.9.5). Tomorrow I will try to reproduce the problem on the first machine (at work) again.

**Comment by astynax** [comment]
I tried to run `stackage-update==0.1.0.2` (installed yesterday) on my work machine. This run was the first one on this machine (no `~/.stackage-update/` was created yet). Result:

``` shell
$ stackage-update
error: unknown option `no-single-branch'
...
```

Then I installed `stackage-update==0.1.0.0` into new sandbox and ran it. Result:

``` shell
$ .cabal-sandbox/bin/stackage-update 
Cloning into 'all-cabal-files'...
remote: Counting objects: 116697, done.
...
Resolving deltas: 100% (45277/45277), done.
```

And then I executed the first one:

``` shell
$ stackage-update
$ # no errors and no output (because the repo was not changed from the previous run I think)
```

I deleted a `~/.stackage-update/` and ran `stackage-update` (first one, 0.1.0.2) again:

``` shell
$ stackage-update 
error: unknown option `no-single-branch'
...
```

And then the sandboxed one (0.1.0.0):

``` shell
$ .cabal-sandbox/bin/stackage-update 
Cloning into 'all-cabal-files'...
remote: Counting objects: 116697, done.
...
```

For now on this particular machine `0.1.0.0` works fine and the `0.1.0.2` works if the `~/.stackage-update/` already exists

**Comment by snoyberg** [comment]
Can you test the current version on `master`, which includes code to check the Git version?

**Comment by astynax** [comment]
Current version on `master` works fine!

**Comment by snoyberg** [comment]
Thanks for confirming, new version 0.1.0.3 is now on Hackage.
