### ISSUE TITLE
Allow uploading documentation to hackage

### ISSUE THREAD

**Issue by soenkehahn** [fpco/stackage-update#7]
This was mentioned here:
https://www.fpcomplete.com/blog/2015/04/announcing-stackage-upload#future-enhancements.
It would be really nice to have.

**Comment by snoyberg** [comment]
I'm unlikely to implement this myself, as I'm more than a little frustrated right now with Hackage's inability to display documentation correctly (expect a blog post on that soon). I'll be happy to merge in a PR though, although I think you'd want to send it to stackage-upload, not stackage-update.

**Comment by soenkehahn** [comment]
Oh, yes, this is the wrong repo, sorry. Should I close this and open one in `stackage-upload`?

Is your frustration only about it often not building the docs or are there other problems?

**Comment by snoyberg** [comment]
Yeah, reopening in that repo makes sense.

You can see my frustration coming to life here: https://github.com/haskell/hackage-server/pull/356. I wrote a [blog post](https://gist.github.com/snoyberg/9650e986e176aa511022) with more information, but I'm debating whether it's worth facing the inevitable flame war by posting it.
